# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('contact', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('lostTime', models.DateTimeField(db_index=True)),
                ('lostPlace', models.CharField(max_length=128)),
                ('reward', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('contact', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('lostTime', models.DateTimeField(db_index=True)),
                ('lostPlace', models.CharField(max_length=128)),
                ('reward', models.CharField(max_length=128)),
            ],
        ),
    ]
