# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('publisherId', models.IntegerField(default=0)),
                ('picUrl', models.CharField(default=None, max_length=4096)),
                ('publishTime', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('contacts', models.CharField(default=None, max_length=128)),
                ('contactType', models.CharField(default=None, max_length=128)),
                ('contactNumber', models.CharField(default=None, max_length=128)),
                ('description', models.TextField()),
                ('foundTime', models.DateTimeField(db_index=True)),
                ('foundPlace', models.CharField(default=None, max_length=128)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('picUrl', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('contacts', models.CharField(default=None, max_length=128)),
                ('contactType', models.CharField(default=None, max_length=128)),
                ('contactNumber', models.CharField(default=None, max_length=128)),
                ('description', models.TextField()),
                ('lostTime', models.DateTimeField(db_index=True)),
                ('lostPlace', models.CharField(default=None, max_length=128)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('reward', models.CharField(default=None, max_length=128)),
                ('picUrl', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wechat.User'),
        ),
        migrations.AddField(
            model_name='found',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wechat.User'),
        ),
    ]
