# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-24 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20161223_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlost',
            old_name='picUrl',
            new_name='picUrl0',
        ),
        migrations.AddField(
            model_name='adminlost',
            name='picUrl1',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='adminlost',
            name='picUrl2',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='adminlost',
            name='picUrl3',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
