# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20161228_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlost',
            name='picUrl',
            field=models.CharField(default=None, max_length=4096),
        ),
    ]
