# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-27 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wechat.User'),
        ),
        migrations.AddField(
            model_name='lost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wechat.User'),
        ),
    ]
