# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20161127_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='status',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
