# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20161202_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='picUrl',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='lost',
            name='picUrl',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='found',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lost',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
