# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20161203_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found',
            old_name='lostPlace',
            new_name='foundPlace',
        ),
        migrations.RenameField(
            model_name='found',
            old_name='lostTime',
            new_name='foundTime',
        ),
        migrations.RemoveField(
            model_name='found',
            name='reward',
        ),
    ]
