# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_auto_20161204_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='found',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lost',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lost',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
