# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20161205_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='found',
            name='contactNumber',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='found',
            name='contactType',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='found',
            name='contacts',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='lost',
            name='contactNumber',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='lost',
            name='contactType',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='lost',
            name='contacts',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
