# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20161211_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('picUrl', models.CharField(default=None, max_length=256)),
                ('publishTime', models.DateTimeField(db_index=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='found',
            name='foundPlace',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lostPlace',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='lost',
            name='reward',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
